# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.9
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_bkl_c', [dirname(__file__)])
        except ImportError:
            import _bkl_c
            return _bkl_c
        if fp is not None:
            try:
                _mod = imp.load_module('_bkl_c', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _bkl_c = swig_import_helper()
    del swig_import_helper
else:
    import _bkl_c
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def doEvalExpr(*args):
  return _bkl_c.doEvalExpr(*args)
doEvalExpr = _bkl_c.doEvalExpr

def proxydict_create():
  return _bkl_c.proxydict_create()
proxydict_create = _bkl_c.proxydict_create

def proxydict_hijack(*args):
  return _bkl_c.proxydict_hijack(*args)
proxydict_hijack = _bkl_c.proxydict_hijack

def proxydict_add(*args):
  return _bkl_c.proxydict_add(*args)
proxydict_add = _bkl_c.proxydict_add
class ProxyDictionary:
    def __init__(self):
        self.dict = {}
        self._catchall = {}
        self.data = proxydict_create()
        proxydict_hijack(self.data, self.dict)
        self.add(self._catchall)
    def add(self, d):
        proxydict_add(self.data, d)

# This file is compatible with both classic and new-style classes.


